Repository PeggyJV/ocular, pull requests merged in 2022-03, with the labels that each got.

#16 readme update
  README.md
Labels: documentation

#17 Collin/module restructure
  ocular/src/chain.rs
  ocular/src/chain/client.rs
  ocular/src/chain/client/query.rs
  ocular/src/chain/config.rs
  ocular/src/chain/info.rs
  ocular/src/chain/registry.rs
  ocular/src/lib.rs
  ocular/tests/rpc.rs
  ocular_cli/src/commands/chains/show.rs
  ocular_cli/src/config.rs
Labels: refactor

#7 Abstract Keyring with filestore implementation
  Cargo.lock
  ocular/Cargo.toml
  ocular/src/chain/client.rs
  ocular/src/chain/config.rs
  ocular/src/chain/info.rs
  ocular/src/error.rs
  ocular/src/keyring.rs
  ocular/src/lib.rs
  ocular_cli/tests/acceptance.rs
Labels: enhancement
